-- ============================================================================
-- Módulo Mercado Libre — migración base (PR1 / tarea T2)
-- Correr en el SQL Editor de Supabase ANTES de deployar el código de PR2.
--
-- Todo es aditivo: columnas nuevas con default y tablas nuevas. No toca datos
-- existentes, no toma locks largos, no requiere rollback de migración.
--
-- La PARTE D (canal 'mercadolibre') es la única que necesita inspección previa.
-- Leer el comentario de esa sección antes de correrla.
-- ============================================================================


-- ── PARTE A — Match de publicaciones ML ↔ productos internos ────────────────
-- ml_item_id es el ID de la publicación ("MLA123456789"). UNIQUE porque dos
-- productos internos no pueden apuntar a la misma publicación: si pasara, el
-- match del webhook sería ambiguo y descontaría stock del producto equivocado.
-- El UNIQUE ya crea el índice btree que usa el lookup del webhook.

ALTER TABLE public.productos
  ADD COLUMN IF NOT EXISTS ml_item_id text;

CREATE UNIQUE INDEX IF NOT EXISTS productos_ml_item_id_key
  ON public.productos (ml_item_id)
  WHERE ml_item_id IS NOT NULL;   -- parcial: permite muchos NULL (productos sin publicar en ML)


-- ── PARTE B — Idempotencia y conciliación de pedidos ───────────────────────
-- ml_order_id es la clave de idempotencia: ML reenvía la misma notificación
-- varias veces y el UNIQUE es la última línea de defensa contra pedidos
-- duplicados, incluso si dos webhooks entran en paralelo.

ALTER TABLE public.pedidos
  ADD COLUMN IF NOT EXISTS ml_order_id text;

CREATE UNIQUE INDEX IF NOT EXISTS pedidos_ml_order_id_key
  ON public.pedidos (ml_order_id)
  WHERE ml_order_id IS NOT NULL;  -- parcial: los pedidos no-ML tienen NULL

-- conciliado = false marca un pedido de ML cuyo item no matcheó ningún producto
-- interno. Default true para que todo lo existente y todo lo no-ML quede sano.
ALTER TABLE public.pedidos
  ADD COLUMN IF NOT EXISTS conciliado boolean NOT NULL DEFAULT true;

-- Índice para el contador de "sin conciliar" del dashboard (T7).
CREATE INDEX IF NOT EXISTS pedidos_sin_conciliar_idx
  ON public.pedidos (conciliado)
  WHERE conciliado = false;


-- ── PARTE C — Credenciales OAuth y auditoría de importaciones ──────────────

-- Una fila por cuenta de ML. Hoy se usa una sola, pero la tabla (en vez de
-- env vars) es lo que deja la puerta abierta a multi-cuenta sin migración.
CREATE TABLE IF NOT EXISTS public.ml_credenciales (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  seller_id     text NOT NULL UNIQUE,
  nickname      text,
  access_token  text NOT NULL,
  refresh_token text NOT NULL,
  -- Momento de expiración del access_token (ML da ~6h).
  expires_at    timestamptz NOT NULL,
  -- ACTIVO = el refresh viene funcionando.
  -- DEGRADADO = el refresh falló; hace falta re-login manual. Dispara alerta.
  estado        text NOT NULL DEFAULT 'activo'
                CHECK (estado IN ('activo', 'degradado')),
  ultimo_error  text,
  created_at    timestamptz NOT NULL DEFAULT now(),
  updated_at    timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.ml_credenciales IS
  'Tokens OAuth de Mercado Libre. Escrita solo por el cliente service-role desde /api/ml/oauth/*.';

-- Auditoría: una fila por notificación recibida. Es el runbook — si dentro de
-- tres semanas aparece una venta rara, se reconstruye qué pasó desde acá.
CREATE TABLE IF NOT EXISTS public.ml_importaciones (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ml_order_id   text NOT NULL,
  resultado     text NOT NULL
                CHECK (resultado IN (
                  'importada',        -- pedido creado ok
                  'duplicada',        -- ya existía: no-op idempotente
                  'sin_conciliar',    -- importada pero algún item no matcheó
                  'ignorada',         -- orden no pagada todavía, o notificación sin resource
                  'error'             -- falló: ver detalle
                )),
  pedido_id     bigint REFERENCES public.pedidos(id) ON DELETE SET NULL,
  detalle       text,
  payload       jsonb,                -- respuesta cruda de la Orders API
  created_at    timestamptz NOT NULL DEFAULT now()
);

-- Para reconstruir el historial de una orden puntual.
CREATE INDEX IF NOT EXISTS ml_importaciones_order_idx
  ON public.ml_importaciones (ml_order_id, created_at DESC);

-- Para el panel de errores recientes.
CREATE INDEX IF NOT EXISTS ml_importaciones_resultado_idx
  ON public.ml_importaciones (resultado, created_at DESC);

COMMENT ON TABLE public.ml_importaciones IS
  'Log de auditoría de notificaciones de ML. Append-only; nunca se borra desde la app.';


-- ── PARTE D — Canal de venta 'mercadolibre' ────────────────────────────────
--
-- ⚠️ LEER ANTES DE CORRER.
--
-- No sé cómo está tipada `pedidos.canal_venta` en la base (puede ser text
-- libre, un enum de Postgres, o text con un CHECK). El bloque de abajo:
--   · si es ENUM  → agrega el valor automáticamente;
--   · si es TEXT libre → no hace nada (no hace falta);
--   · si tiene CHECK → NO lo toca, y te imprime la definición actual del
--     constraint en el panel de mensajes, para reescribirlo a mano.
--
-- Reescribir un CHECK a ciegas es la única operación de esta migración que
-- podría romper inserts existentes, así que queda explícitamente manual.
-- Si imprime un CHECK, pasame el texto y te doy el ALTER exacto.

DO $$
DECLARE
  v_typtype  "char";
  v_typname  text;
  v_check    record;
BEGIN
  SELECT t.typtype, t.typname
    INTO v_typtype, v_typname
  FROM pg_attribute a
  JOIN pg_type t ON t.oid = a.atttypid
  WHERE a.attrelid = 'public.pedidos'::regclass
    AND a.attname  = 'canal_venta'
    AND a.attnum > 0;

  IF v_typtype = 'e' THEN
    EXECUTE format(
      'ALTER TYPE public.%I ADD VALUE IF NOT EXISTS %L',
      v_typname, 'mercadolibre'
    );
    RAISE NOTICE 'canal_venta es el enum %: valor ''mercadolibre'' agregado.', v_typname;
    RAISE NOTICE 'Ojo: el valor nuevo de un enum recién se puede usar en otra transacción.';
    RETURN;
  END IF;

  FOR v_check IN
    SELECT c.conname, pg_get_constraintdef(c.oid) AS def
    FROM pg_constraint c
    WHERE c.conrelid = 'public.pedidos'::regclass
      AND c.contype  = 'c'
      AND pg_get_constraintdef(c.oid) ILIKE '%canal_venta%'
  LOOP
    RAISE NOTICE 'ACCION MANUAL — constraint % sobre canal_venta:', v_check.conname;
    RAISE NOTICE '  %', v_check.def;
    RAISE NOTICE '  Reescribilo agregando ''mercadolibre'' a la lista de valores.';
    RETURN;
  END LOOP;

  RAISE NOTICE 'canal_venta es texto libre sin CHECK: no hace falta migrar nada.';
END $$;


-- ── Verificación ───────────────────────────────────────────────────────────
-- Correr después y confirmar que devuelve las 3 columnas y las 2 tablas.

SELECT 'columna' AS tipo, table_name || '.' || column_name AS objeto
FROM information_schema.columns
WHERE table_schema = 'public'
  AND (   (table_name = 'productos' AND column_name = 'ml_item_id')
       OR (table_name = 'pedidos'   AND column_name IN ('ml_order_id', 'conciliado')))
UNION ALL
SELECT 'tabla', table_name
FROM information_schema.tables
WHERE table_schema = 'public'
  AND table_name IN ('ml_credenciales', 'ml_importaciones')
ORDER BY 1, 2;
